# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 11:36
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='http://ba3d96e768581514f6ec-e6b856593874a8f38a8aa2d89e1f03ce.r54.cf2.rackcdn.com/default_food_large.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='instructions',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
