# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal',
            field=models.CharField(choices=[('MN', 'Main'), ('DS', 'Dessert'), ('ST', 'Starter')], default='MN', max_length=2),
        ),
    ]
