# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20160502_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(600), django.core.validators.MinValueValidator(0)]),
        ),
    ]
