# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20160502_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeInstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
