# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20160502_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinstruction',
            name='instruction',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
