# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20160502_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstruction',
            name='step',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
    ]
