# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20160502_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinstruction',
            name='ingredient',
            field=models.CharField(default='', max_length=100),
        ),
    ]
