# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20160503_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstruction',
            name='unit',
            field=models.CharField(choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('c', 'cup'), ('pt', 'pint'), ('gal', 'gallon'), ('L', 'liter'), ('cc', 'millimeter'), ('lb', 'pound'), ('oz', 'ounce'), ('mg', 'milligram'), ('g', 'gram'), ('kg', 'kilogram'), ('in', 'inch'), ('cm', 'cm'), ('mm', 'mm')], default='tsp', max_length=10),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
