# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20160503_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinstruction',
            name='with_unit',
            field=models.CharField(choices=[(0, 'No unit'), (1, 'Has unit')], default=0, max_length=10),
        ),
    ]
