# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipeinstruction_with_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstruction',
            name='with_unit',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0),
        ),
    ]
