# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20160503_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeinstruction',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeinstruction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='recipeinstruction',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='recipeinstruction',
            name='with_unit',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
