# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20160503_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='recipeinstruction',
            name='instruction',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
